language: node_js

node_js:
  - 8
  - 10
  - 11
  - 12

sudo: false

matrix:
  fast_finish: true

cache: yarn

before_install:
  - travis_retry npm i -g yarn

script:
  - cd packages/eslint-config-inpsyde && yarn && yarn test && cd ../..
