language: node_js

node_js:
  - 4
  - 5
  - 6

sudo: false

matrix:
  fast_finish: true

cache: yarn

before_install:
  - travis_retry npm i -g yarn

script:
  - cd packages/eslint-config-inpsyde && yarn && yarn run test && cd ../..
